sudo: required
services:
  - docker

before install:
  - docker build -t kenken64/subsdevices:v1 -f Dockerfile.dev .

script: 
  - docker run kenken64/subsdevices:v1 npm run test -- --coverage
